[package]
org = "wso2healthcare"
name = "PatientAPIwithEP"
version = "0.2.1"
export = ["PatientAPIwithEP"]
distribution = "2201.3.1"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Patient","r4","international"]

[build-options]
observabilityIncluded = true
